name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      kafka:
        image: confluentinc/cp-kafka:latest
        ports:
          - 9092:9092
      zookeeper:
        image: confluentinc/cp-zookeeper:latest
        ports:
          - 2181:2181

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies for producer
        run: |
          cd producer
          npm install

      - name: Install dependencies for consumer
        run: |
          cd consumer
          npm install

      - name: Run tests
        run: |
          cd producer
          npm test
          cd ../consumer
          npm test

